// <auto-generated />
using System;
using GLAT.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GLAT.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303174546_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GLAT.Domain.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("LastUpdated")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Assets", (string)null);
                });

            modelBuilder.Entity("GLAT.Domain.Entities.TelemetryLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.ToTable("TelemetryLogs", (string)null);
                });

            modelBuilder.Entity("GLAT.Domain.Entities.Asset", b =>
                {
                    b.OwnsOne("GLAT.Domain.Entities.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("AssetId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float")
                                .HasColumnName("Location_Latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float")
                                .HasColumnName("Location_Longitude");

                            b1.HasKey("AssetId");

                            b1.ToTable("Assets");

                            b1.WithOwner()
                                .HasForeignKey("AssetId");
                        });

                    b.Navigation("Location")
                        .IsRequired();
                });

            modelBuilder.Entity("GLAT.Domain.Entities.TelemetryLog", b =>
                {
                    b.HasOne("GLAT.Domain.Entities.Asset", null)
                        .WithMany()
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("GLAT.Domain.Entities.SensorReadings", "Sensors", b1 =>
                        {
                            b1.Property<Guid>("TelemetryLogId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Pressure")
                                .HasColumnType("float")
                                .HasColumnName("Sensor_Pressure");

                            b1.Property<double>("Temperature")
                                .HasColumnType("float")
                                .HasColumnName("Sensor_Temperature");

                            b1.Property<double>("Vibration")
                                .HasColumnType("float")
                                .HasColumnName("Sensor_Vibration");

                            b1.HasKey("TelemetryLogId");

                            b1.ToTable("TelemetryLogs");

                            b1.WithOwner()
                                .HasForeignKey("TelemetryLogId");
                        });

                    b.Navigation("Sensors")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
